server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8001/eureka/
zuul:
  prefix: /glarimy
  routes:
    admin-service:
      path: /admin/**
      serviceId: GLARIMY-ADMIN-SERVICE
    employee-service:
      path: /directory/**
      serviceId: GLARIMY-EMPLOYEE-SERVICE
    static:
      path: /home/**